// Field-driven configuration for generic CRUD modules.
// type: text | textarea | number | date | select | url

export const MODULES = {
  clients: {
    label: "Client",
    title: "Client Command Center",
    subtitle: "Your professional CRM — every relationship, tracked.",
    layout: "table",
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "company", label: "Company", type: "text" },
      { name: "country", label: "Country", type: "text" },
      { name: "email", label: "Email", type: "text" },
      { name: "discord", label: "Discord", type: "text" },
      { name: "whatsapp", label: "WhatsApp", type: "text" },
      { name: "status", label: "Status", type: "select", options: ["lead", "active", "ongoing", "completed", "inactive"], default: "lead" },
      { name: "revenue", label: "Revenue Generated", type: "number", default: 0 },
      { name: "project_count", label: "Projects", type: "number", default: 0 },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    columns: ["name", "company", "country", "status", "revenue", "project_count"],
  },
  youtube_videos: {
    label: "Video",
    title: "YouTube Command Center",
    subtitle: "Idea to publish — your full content pipeline.",
    layout: "table",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "category", label: "Category", type: "text" },
      { name: "status", label: "Stage", type: "select", options: ["idea", "scripting", "recording", "editing", "thumbnail", "scheduled", "published"], default: "idea" },
      { name: "publish_date", label: "Publish Date", type: "date" },
      { name: "views", label: "Views", type: "number", default: 0 },
      { name: "script", label: "Script / Notes", type: "textarea" },
    ],
    columns: ["title", "category", "status", "publish_date", "views"],
  },
  content_ideas: {
    label: "Idea",
    title: "Content Ideas",
    subtitle: "Capture every spark before it fades.",
    layout: "cards",
    fields: [
      { name: "title", label: "Idea", type: "text", required: true },
      { name: "category", label: "Category", type: "text" },
      { name: "status", label: "Status", type: "select", options: ["idea", "in_progress", "done"], default: "idea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    columns: ["title", "category", "status"],
  },
  ai_tools: {
    label: "AI Tool",
    title: "AI Tools Vault",
    subtitle: "Your arsenal of intelligence — organized and rated.",
    layout: "cards",
    fields: [
      { name: "name", label: "Tool Name", type: "text", required: true },
      { name: "category", label: "Category", type: "text" },
      { name: "url", label: "Launch URL", type: "url" },
      { name: "rating", label: "Rating (1-5)", type: "number", default: 5 },
      { name: "favorite", label: "Favorite", type: "select", options: ["no", "yes"], default: "no" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    columns: ["name", "category", "rating", "favorite"],
  },
  team_members: {
    label: "Team Member",
    title: "Team Management",
    subtitle: "Build the empire — manage your people.",
    layout: "cards",
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "role", label: "Role", type: "text" },
      { name: "email", label: "Email", type: "text" },
      { name: "status", label: "Status", type: "select", options: ["active", "inactive"], default: "active" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    columns: ["name", "role", "email", "status"],
  },
};

export const SELECT_COLORS = {
  lead: "text-zinc-300 bg-white/5",
  active: "text-lime-400 bg-lime-400/10",
  ongoing: "text-teal-300 bg-teal-400/10",
  completed: "text-blue-300 bg-blue-400/10",
  inactive: "text-zinc-500 bg-white/5",
  idea: "text-zinc-300 bg-white/5",
  scripting: "text-purple-300 bg-purple-400/10",
  recording: "text-orange-300 bg-orange-400/10",
  editing: "text-yellow-300 bg-yellow-400/10",
  thumbnail: "text-pink-300 bg-pink-400/10",
  scheduled: "text-teal-300 bg-teal-400/10",
  published: "text-lime-400 bg-lime-400/10",
  in_progress: "text-teal-300 bg-teal-400/10",
  done: "text-lime-400 bg-lime-400/10",
  paused: "text-zinc-500 bg-white/5",
  yes: "text-lime-400 bg-lime-400/10",
  no: "text-zinc-500 bg-white/5",
};
